name: 'Hello World'
description: 'Greet someone'
inputs:
  token:  # id of input
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  tag:
    description: 'Release tag'
    required: true
runs:
  using: "composite"
  steps:
    - name: Delete release if it exists
      run: |
        RELEASE_ID=$(gh release view ${INPUT_TAG} --json id -q .id || echo "")
        if [ -n "$RELEASE_ID" ]; then
          gh release delete latest-workflow-run --yes
          gh api --method DELETE repos/${{ github.repository }}/git/refs/tags/${INPUT_TAG} || echo "Tag not found"
        else
          echo "No existing release found"
        fi
      shell: bash
      env:
        GH_TOKEN: ${INPUT_TOKEN}
